# Default values: 'https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml'
# Path:
#    ~/.config/yazi/keymap.toml        (Unix-like systems)
#    %AppData%\yazi\config\keymap.toml (Windows)
#
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [

    # --------------------------------------------------------------------------
    # Anulando keymappings
    # --------------------------------------------------------------------------

    # Se anula el keymapping built-in "f" ('filtrado de vista actual de yazi'). Se remplazara por "s".
    { on = "f", run = "noop" },

    # Se anula el keymapping built-in "S" ('busqueda de archivos por su contenido dentro de yazi'). Se remplazara por "s, c".
    { on = "S", run = "noop" },

    # Se anula el keymapping built-in "Ctrl + a" ('toggle all') para dejar libre a uso tmux. Se remplazara por "A"
    { on = "<C-a>", run = "noop" },


    # --------------------------------------------------------------------------
    # Nuevos keymappings
    # --------------------------------------------------------------------------

    # Toogle (maximiza/restaura) el zoom del panel 'preview' (oculta/muestra los paneles 'parent' y 'current')
    # > Requiere el plugin 'toogle-pane'
    #   > Info                : https://github.com/dawsers/toggle-view.yazi/blob/master/init.lua
    #   > Descarga del plugin : ya pkg add yazi-rs/plugins:toggle-pane
    #{ on = [ "T" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },

    # Comando para copiar la ruta relativa de objeto actual selecionado (no usar los reservados 'c', 'd', 'f' y 'n')
    { on = [ "c", "w" ], run = "plugin go-fs -- copycb --pathtype=rootwd", desc = "Copy relative path (Root WD)" },
    { on = [ "c", "g" ], run = "plugin go-fs -- copycb --pathtype=rootgit", desc = "Copy relative path (Root git)" },

    # Comandos de busqueda integrada en la vista de Yazi
    { on = [ "f", "x" ], run = "search --via=fd", desc = "Find files (basic)" },
    { on = [ "f", "y" ], run = "search --via=rg", desc = "Find files by content (basic)" },

    # Comandos de busqueda integrada en la vista de Yazi
    { on = [ "f", "n" ], run = "search --via=fd", desc = "Find files by name (basic)" },
    { on = [ "f", "c" ], run = "search --via=rg", desc = "Find files by content (basic)" },

    # Comandos de busqueda externa usando 'fzf'
    { on = [ "f", "w" ], run = "plugin fzf-fd -- file   --findpath=rootwd" , desc = "Find files (Root WD) & Select" },
    { on = [ "f", "g" ], run = "plugin fzf-fd -- file   --findpath=rootgit", desc = "Find files (Root git) & Select" },
    { on = [ "f", "c" ], run = "plugin fzf-fd -- file   --findpath=cwd"    , desc = "Find files (CWD) & Select" },
    { on = [ "f", "d" ], run = "plugin fzf-fd -- folder --findpath=rootwd" , desc = "Find directories (Root WD) & Select" },
    { on = [ "f", "1" ], run = "plugin fzf-fd -- folder --findpath=rootgit", desc = "Find directories (Root git) & Select" },
    { on = [ "f", "2" ], run = "plugin fzf-fd -- folder --findpath=cwd"    , desc = "Find directories (CWD) & Select" },

    # Comandos para editar archivos de texto en una nueva ventana de la terminal (opcionalmente realizan una busqueda en los archivos de texto)
    { on = [ "e", "w" ], run = "plugin fzf-rg -- rootwd --editor=vim --findpath=rootwd"   , desc = "Find content (Root WD) & Edit VIM (Root WD)" },
    { on = [ "e", "1" ], run = "plugin fzf-rg -- rootwd --editor=nvim --findpath=rootwd"  , desc = "Find content (Root WD) & Edit NVIM (Root WD)" },
    { on = [ "e", "g" ], run = "plugin fzf-rg -- rootgit --editor=vim --findpath=rootgit" , desc = "Find content (Root git) & Edit VIM (Root git)" },
    { on = [ "e", "2" ], run = "plugin fzf-rg -- rootgit --editor=nvim --findpath=rootgit", desc = "Find content (Root git) & Edit NVIM (Root git)" },
    { on = [ "e", "c" ], run = "plugin fzf-rg -- rootwd --editor=vim --findpath=cwd"      , desc = "Find content (CWD) & Edit VIM (Root WD)" },
    { on = [ "e", "3" ], run = "plugin fzf-rg -- rootwd --editor=nvim --findpath=cwd"     , desc = "Find content (CWD) & Edit NVIM (Root WD)" },
    { on = [ "e", "d" ], run = "plugin fzf-rg -- rootgit --editor=vim --findpath=cwd"     , desc = "Find content (CWD) & Edit VIM (Root git)" },
    { on = [ "e", "4" ], run = "plugin fzf-rg -- rootgit --editor=nvim --findpath=cwd"    , desc = "Find content (CWD) & Edit NVIM (Root git)" },

    { on = [ "e", "a" ], run = "plugin fzf-fd -- rootwd --editor=vim --findpath=rootwd"   , desc = "Find files (Root WD) & Edit VIM (Root WD)" },
    { on = [ "e", "5" ], run = "plugin fzf-fd -- rootwd --editor=nvim --findpath=rootwd"  , desc = "Find files (Root WD) & Edit NVIM (Root WD)" },
    { on = [ "e", "b" ], run = "plugin fzf-fd -- rootgit --editor=vim --findpath=rootgit" , desc = "Find files (Root git) & Edit VIM (Root git)" },
    { on = [ "e", "6" ], run = "plugin fzf-fd -- rootgit --editor=nvim --findpath=rootgit", desc = "Find files (Root git) & Edit NVIM (Root git)" },
    { on = [ "e", "e" ], run = "plugin fzf-fd -- rootwd --editor=vim --findpath=cwd"      , desc = "Find files (CWD) & Edit VIM (Root WD)" },
    { on = [ "e", "7" ], run = "plugin fzf-fd -- rootwd --editor=nvim --findpath=cwd"     , desc = "Find files (CWD) & Edit NVIM (Root WD)" },
    { on = [ "e", "f" ], run = "plugin fzf-fd -- rootgit --editor=vim --findpath=cwd"     , desc = "Find files (CWD) & Edit VIM (Root git)" },
    { on = [ "e", "8" ], run = "plugin fzf-fd -- rootgit --editor=nvim --findpath=cwd"    , desc = "Find files (CWD) & Edit NVIM (Root git)" },

    { on = [ "e", "g" ], run = "plugin go-fs -- editfiles --type=rootwd --editor=vim" , desc = "Edit current files VIM (Root WD)" },
    { on = [ "e", "9" ], run = "plugin go-fs -- editfiles --type=rootwd --editor=nvim", desc = "Edit current files NVIM (Root WD)" },

    { on = [ "e", "h" ], run = "plugin go-fs -- editfiles --type=rootgit --editor=vim" , desc = "Edit current files VIM (Root git)" },
    { on = [ "e", "0" ], run = "plugin go-fs -- editfiles --type=rootgit --editor=nvim", desc = "Edit current files NVIM (Root git)" },

    # Comandos para ir a directorios especiales (no usar los reservados 'c', 'd', 'h', '<scape>' y 'f')
    { on = [ "g", "1" ], run = "cd ~/vimfiles", desc = "Go VIM data" },
    { on = [ "g", "2" ], run = "cd %LOCALAPPDATA%/nvim", desc = "Go NVIM config" },
    { on = [ "g", "3" ], run = "cd %LOCALAPPDATA%/nvim-data", desc = "Go NVIM data folder" },
    { on = [ "g", "4" ], run = "cd ~/vimfiles/pack", desc = "Go VIM packages" },
    { on = [ "g", "5" ], run = "cd %LOCALAPPDATA%/nvim-data/site/pack", desc = "Go NVIM packages" },
    { on = [ "g", "6" ], run = "cd %APPDATA%", desc = "Go %APPDATA%" },
    { on = [ "g", "7" ], run = "cd %TEMP%", desc = "Go %TEMP%" },
    { on = [ "g", "8" ], run = "cd %LOCALAPPDATA%", desc = "Go %LOCALAPPDATA%" },
    { on = [ "g", "9" ], run = "cd C:", desc = "Go C:" },
    { on = [ "g", "0" ], run = "cd D:", desc = "Go D:" },

    { on = [ "g", "w" ], run = "plugin go-fs -- gofolder --pathtype=rootwd", desc = "Go Root WD folder" },
    { on = [ "g", "g" ], run = "plugin go-fs -- gofolder --pathtype=rootgit", desc = "Go Root git folder" },
    #{ on = [ "g", "n" ], run = "cd D:/vaults/notes", desc = "Go My Notes (Obsidian vaults)" },


    # --------------------------------------------------------------------------
    # Redefiniendo keymappings predeterminados
    # --------------------------------------------------------------------------

    # Se redefine el 'filtrado de vista actual de yazi' (el keymapping por defecto usa "f").
    { on = "s", run = "filter --smart", desc = "Filter files" },

    # Se redefine el 'toggle all' (el keymapping por defecto usa "A").
    { on = "A",   run = "toggle_all --state=on", desc = "Select all files" },

]
