# Sesiones especificas para el usuario

[[session]]
name = "config wezterm"
path = "~/.config/wezterm"
startup_command = "vim wezterm.lua custom_config.lua"

[[session]]
name = "downloads"
path = "/dt9/tmp/downloads"

[[session]]
name = "upload movies"
path = "/dt2/tmp"
preview_command = "eza --tree --color=always --icons always -L 4 {}"
startup_command = "~/.files/shell/bash/bin/tmux_layout/tmx_upload_movies.bash"
