##
## Main Kitty Config
## > Info:
##   > General      : https://sw.kovidgoyal.net/kitty/conf/#
##


# Usar Wayland
linux_display_server wayland


#------------------------------------------------------------------------
# UI> Font settings
#------------------------------------------------------------------------

font_family               family="JetBrainsMono Nerd Font Mono"
bold_font                 auto
italic_font               auto
bold_italic_font          auto

font_size                 10

# Se desactivan al pasar el cursor (útil para programar)
disable_ligatures         cursor


#------------------------------------------------------------------------
# UI> Windows settings
#------------------------------------------------------------------------

# NO recordar el ultimo tamaño de la emulador
remember_window_size      no

# Tamaño inicial de la ventana
initial_window_width      150c
initial_window_height     30c

# Establecer un padding de 4px en los cuatro lados del contenido
window_padding_width      2


#------------------------------------------------------------------------
# UI> Tab settings
#------------------------------------------------------------------------

# Tab-bar settings
tab_bar_min_tabs          2
tab_bar_edge              bottom
tab_bar_style             powerline
tab_powerline_style       slanted
tab_title_template        " {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template " {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "


#------------------------------------------------------------------------
# UI> Scrollback
#------------------------------------------------------------------------

# Scrollback size
scrollback_lines          5000


#------------------------------------------------------------------------
# UI> Prompt
#------------------------------------------------------------------------

# Cursor> Forma del cursor (block, beam, underline)
#cursor_shape              block

# Cursor> Habilitar el parpadeo (1). Con 0 se desabilita
#cursor_blink_interval     0

# Cursor> Frecuencia de parapadeo de cursor
# > Si es '0' nunca parpadea
#cursor_blink_interval     0.5


#------------------------------------------------------------------------
# UI> Theme
#------------------------------------------------------------------------

include                   theme.conf


#------------------------------------------------------------------------
# Clipboard settings
#------------------------------------------------------------------------

# Usar el clipboard primario (Wayland no soporta el clipboard secundario)
clipboard_control         write-clipboard write-primary

# Copiado automatico del portapapeles
#copy_on_select            yes


#------------------------------------------------------------------------
# Keymapping settings
#------------------------------------------------------------------------

# Remover el default keymapping
clear_all_shortcuts       yes

# Time allowed between leader and next key
map_timeout               2.0
include                   keymappings.conf


#------------------------------------------------------------------------
# General settings
#------------------------------------------------------------------------

#strip_trailing_spaces      smart
#focus_follows_mouse        yes
#terminal_select_modifiers  ctrl

# Optional visual           bell
#enable_audio_bell          no
#visual_bell_duration       0.1


#------------------------------------------------------------------------
# Others settings
#------------------------------------------------------------------------

#include_if_exists         custom_config.conf
include                   custom_config.conf
