##
## Custom Kitty Config
## > Info:
##   > General      : https://sw.kovidgoyal.net/kitty/conf/#
##


#------------------------------------------------------------------------
# Tiling Manager settings
#------------------------------------------------------------------------

# Ocultar la barra de titulo y borde de la ventana
#hide_window_decorations     yes

# Ocultar la barra de tab
#show_tab_bar                no

# Cerrar la ventana si mostrar el digalogo de confirmacion.
#confirm_os_window_close     0

# Rendimiento (baja latencia)
#repaint_delay               8
#input_delay                 1
#sync_to_monitor             yes


#------------------------------------------------------------------------
# Others
#------------------------------------------------------------------------

# Opacidad
#background_opacity         0.95
#dynamic_background_opacity yes
