--
-- Configuration file hyprland
-- Docs:
-- > https://wiki.hypr.land/Configuring/Start/
-- > https://github.com/hyprwm/Hyprland
--

--local mm_ucommon = require("utils.common")

------------------------------------------------------------------------------------
-- Post-Autostart
------------------------------------------------------------------------------------

require("utils.config_generic")
require("utils.monitors")


------------------------------------------------------------------------------------
-- Autostart
------------------------------------------------------------------------------------

-- Variables de entorno Dark theme (GTK application)
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GTK_APPLICATION_PREFER_DARK_THEME", "1")

-- Variable de entorno Dark theme (QT6 application)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- Usando el socket del Agente SSH de OpenSSH (se definira fuere de hyperland en 'enviroment.d'
-- > Las unidades socket de systemd habilitados con inicio automatico (ssh-agent.socket, pipewire.socket, etc),
--   usualmente, se inician antes que se inicia hyprland.
-- > Las unidad 'ssh-agent.socket' crea el socket IPC, crea/inicia el 'ssh-agent.service' pero no define la
--   variable de entorno 'SSH_AUTH_SOCK'.
-- > Por algun motivo, el launcher (en quick shell) no obtiene esta la variable de entorno por mas que se sincronize.
--   Por tal motivo, la variable se definira en el archivo '~/.config/environment.d/91-myvars.conf'
--env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
--env = SSH_AUTH_SOCK,/run/user/1000/ssh-agent.socket


hl.on("hyprland.start", function()

    -- Las variables de entorno existentes (hasta el momento) en hyperland las propaga en el D-BUS y en SystemD
    -- del usuario. Esto no sincroniza las variables de entorno de procesos (unidades systemd, programas) iniciados
    -- o creados antes de esta sentencia.
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")

    -- Activar el target 'hyprland-session.target' el cual internamente activa el target 'graphical-session.target'.
    -- Ello permite unidades systemd que dependan que este target esta activo ya se puedan inicializar, por ejemplo:
    -- Polkit, Barras de Quickshell, programas marcadas por inicio automatico (XGD AutoStart, exec-once de GUI, etc).
    hl.exec_cmd("systemctl --user start hyprland-session.target")

end)


------------------------------------------------------------------------------------
-- Post-Autostart
------------------------------------------------------------------------------------

-- DMS autogenerated configs
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.colors")

-- DMS reserved config
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- Override 'dms.layout' config
require("utils.config_layout")

-- Mi config
require("utils.workspace_rules")
