
[default_session]
preview_command = "eza --tree --color=always --icons always -L 4 {}"
#preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/.files"
startup_command = "vim -c ':Files'"

[[session]]
name = "downloads"
path = "/tempo/download"
#windows = [ "explorer" ]

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "vim tmux.conf tmux_custom.conf"

[[session]]
name = "git config"
path = "~/.config/git"
startup_command = "vim -c ':Files'"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "vim wezterm.lua config.lua"

[[session]]
name = "ssh config"
path = "~/.ssh"
startup_command = "vim config"

[[window]]
name = "explorer"
startup_script = "yazi"
