#More info: https://github.com/containerd/nerdctl/blob/main/docs/config.md

cni_path       = "/var/opt/tools/cni_plugins"
#debug          = false
#debug_full     = false
#address        = "unix:///run/k3s/containerd/containerd.sock"
#namespace      = "k8s.io"
#snapshotter    = "stargz"
#cgroup_manager = "cgroupfs"
#hosts_dir      = ["/etc/containerd/certs.d", "/etc/docker/certs.d"]
#experimental   = true
